package com.loneliess.controller;

public enum  CommandName {
    LOAD_CONE_MAP, ADD_CONE, SAVE_CONE_MAP, CALCULATE_VOLUME_OF_CONE, CALCULATE_SIDE_SURFACE_AREA_OF_CONE,
    CALCULATE_SIDE_SURFACE_AREA, CALCULATE_VOLUME_RATIO, IS_LIES_ON_THE_PLANE_CONE, DELETE_CONE, UPDATE_CONE,

    WRONG_REQUEST
}
